# This file was generated by GoReleaser. DO NOT EDIT.
cask "omassh" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "omassh"],
        chdir:        ".",
        must_succeed: false
  end

  version "0.11.26"

  on_macos do
    on_arm do
      sha256 "507373e0b5713ffe1b31f0a0f9524a47511dd1c855e5bbd0b32deea39957b6b0"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "424869427e3d8d7abc2049b15ae394b89b6ddce57c17ac0d80cbaedcbcd56ef4"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa7b7c4348b8630b88601a6054ac44d3c3c4f36b6e61df0808dc74a518cac6aa"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c5330ae2f2efe5ef33a2e642ced197fd8876b63002d83d7c55197b5e082ac34"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omassh"
  desc "A keyboard-driven SSH client for the terminal"
  homepage "https://github.com/cuonggt/omassh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omassh"

  # No zap stanza required
end
