# This file was generated by GoReleaser. DO NOT EDIT.
cask "omassh" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "omassh"],
        chdir:        ".",
        must_succeed: false
  end

  version "0.10.6"

  on_macos do
    on_arm do
      sha256 "ff4edf5ddc2bff500cf6c02ffe65b239203a730b6a55e22807a12852cf17b5cd"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "19825040592311de43061efe259a8bff97e54e6b8997709fa9813eda107e9162"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b0e580bbb42423ec3a9d758eeb0e4dcafd1f87d0e75956bb523656a9f364fa4"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "07679721c67bedc0d68ed60e9958e986ebf17871342fded711364df0354cb5f7"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omassh"
  desc "A keyboard-driven SSH client for the terminal"
  homepage "https://github.com/cuonggt/omassh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omassh"

  # No zap stanza required
end
