# This file was generated by GoReleaser. DO NOT EDIT.
cask "omassh" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "omassh"],
        chdir:        ".",
        must_succeed: false
  end

  version "0.8.2"

  on_macos do
    on_arm do
      sha256 "0c30c889a8975a31e8af36f4bd31acae078d25c4e1f1d6caef298cf123b0aeaa"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58f0ceec6eaedff8f9d16b10e6eeb88957741a96d0deae164307d39ca3b9c62e"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03b3e63972621703d185fb9f38bf7efc3276e260d307a7051f8da7bd7633d027"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "15127b4ab715bd66cebf19b8031519d1157274833c2d90f94026fd1b60383c53"
      url "https://github.com/cuonggt/omassh/releases/download/v#{version}/omassh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omassh"
  desc "A keyboard-driven SSH client for the terminal"
  homepage "https://github.com/cuonggt/omassh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omassh"

  # No zap stanza required
end
