# This file was generated by GoReleaser. DO NOT EDIT.
cask "rove" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "1437d1477072fa1496f53279b4c09bd7b6eb0930af30ed4c4a1601120b34bef7"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4eb5ca7d14208a97381ba0fbbfaf7148224ed3bcfe3f1bb4a883ffa47b5c6dd"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f7827e950ad9fe1aa2646685fb20a1ddade888fa1a2690b71f43e54fe103a47"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "91a57818689f8918f159740c94eefc8f7252f293a4a3f3112f6540def66840fc"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rove"
  desc "A terminal console for the Linux servers you already reach over ssh"
  homepage "https://github.com/cuonggt/rove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rove"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rove"]
    end
  end

  # No zap stanza required
end
