# This file was generated by GoReleaser. DO NOT EDIT.
cask "rove" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "rove"],
        chdir:        ".",
        must_succeed: false
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "5512a20e339e082a840482aff4bfc531970e935d160b8988c3751f0d4eb6dcbf"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd171a117a8f312d1415e7da53ddf4233b7c595250cea9518b25e88e01829760"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bdecf0b9168dc8521207c0504f98b7326739b42faaaf8c0036b127f8db1992f0"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03a02b9583f58d3026c81be7d519e704418e14382fb80da3d85866567585531d"
      url "https://github.com/cuonggt/rove/releases/download/v#{version}/rove_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rove"
  desc "A terminal console for the Linux servers you already reach over ssh"
  homepage "https://github.com/cuonggt/rove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rove"

  # No zap stanza required
end
